name: Snake Animation

on:
  push:
    branches:
      - main

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Generate snake
        uses: Platane/snk@master
        with:
          github_user: 'Kirito72-hub' # Your GitHub username
          svg_out: 'output/snake.svg'
          # Other options can be added here

      - name: Commit snake
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add output/snake.svg
          git commit -m "Update snake"
          git push
